# \u5F00\u53D1\u73AF\u5883\u914D\u7F6E\u6587\u4EF6
generator:
  jdbc:
    driver: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root

#\u670D\u52A1\u5668\u7AEF\u53E3
application:
  server:
    port: 8080
